### ISSUE TITLE
unable to open web page

### ISSUE THREAD

**Issue by taospartan** [LCAV/easy-dsp#11]
After installation on ubuntu 18.04 the on trying to access from remote pc 'my-board-ip:8081' I get the following error. 

> Forbidden
You don't have permission to access / on this server.

I'm not an apache expert so don't know which settings to change next.

many thanks in advance

tao

**Comment by taospartan** [comment]
Think i've solved it by altering apache2.conf
I changed 

> Require all denied

to

> Require all granted

I've probably boken apaches security but it works!

**Comment by fakufaku** [comment]
Ha ha, that's good news! I suppose some default configuration of apache has changed compared to the ubuntu version we used for this project.
